Сетка на флексах для главной страницы
htmlacademy-htmlcss/1527415-sedona-29 pull request #9
Opened 2020-09-29 17:50 UTC by SokolovaED

2020-09-29 18:18 UTC, ILoyso requested changes
Можно ещё добавить микро сетку для соц сетей в футере и выстроить их в ряд

2020-09-29 18:18 UTC, ILoyso commented on css/style.css
> +}
А давай ещё и переполнение в меню учтем (тем более это один из критериев). Собственно, наша цель - чтобы при любом количестве элементов меню хорошо выглядело :) 
- нужно разрешить флексу перенос
- а там, где задаем выравнивание текста по правому краю, использовать селектор для каждого третьего и каждого четвертого элемента (nth-child(3n) nth-child(4n))

2020-09-29 19:40 UTC, ILoyso requested changes

2020-09-29 19:40 UTC, ILoyso commented on css/style.css
> +}
Я для примера писала именно такие селекторы)) На деле тут чуть сложнее, правильные будут 
```
.navigation-item:nth-child(4n+3)
.navigation-item:nth-child(4n+4)
```

И лучше вместо justify-content: space-between; использовать start, так выглядит лучше, когда при переполнении у нас 5-6-7 элементов (можешь посмотреть с разными значениями)

2020-09-29 19:40 UTC, ILoyso commented on css/style.css
> +  margin-right: 45px;
У нас сейчас у всех текстовых элементов тянутся стандартные верхний и нижний марджины, давай их обнулим. Они нам не нужны, так как их задали не мы и соответственно сейчас не контролируем. Если же нам понадобятся отступы - добавим их уже сами осознанно (вот как ты сейчас правый марджин добавила)
http://joxi.ru/DmB8lMvCz9pwzA

2020-09-29 19:40 UTC, ILoyso commented on css/style.css
> +}
Отступы у кода поехали

2020-09-29 19:40 UTC, ILoyso commented on css/style.css
> +}
Мы везде флексовые свойства пишем рядом, давай по аналогии align-items после display зададим :) когда все единообразно, код читать удобнее и проще

2020-09-29 19:40 UTC, ILoyso commented on hotels.html
> +            <div class="hotel-info">
Удобнее всего здесь строить микро сетку вот так http://joxi.ru/a2Xz4JvTDE9wGr
То есть блок с контентом, в нем две колонки. В левой колонке заголовок на всю ширину, а под ним ещё две колонки. Все флексами строим, соответственно :)

2020-09-29 19:51 UTC, SokolovaED commented on css/style.css
> +}
:)) я и подумала, что решение нестандартное немного, но тебе наверно лучше знать))

2020-09-29 20:03 UTC, ILoyso commented on css/style.css
> +}
Такие штуки проще всего просто сразу проверять :) переполнить менюшку и посмотреть, как оно смотрится

2020-09-30 07:44 UTC, ILoyso requested changes
В какой-то момент пропала минимальная высота у .page-wrapper и футер перестал "приклеиваться" к нижней части экрана
http://joxi.ru/vAWzXNjTqpZM72

2020-09-30 07:44 UTC, ILoyso commented on css/style.css
> +}
Ширина тут не 100%, там ведь блок с рейтингом должен справа ещё уместиться, так что убираем

А чтобы рейтинг так не растягивало, нужно для hotel-info align-items правильный задать

2020-09-30 07:44 UTC, ILoyso commented on css/style.css
> +}
Авто марджин тут и не нужен, флекс у родителя все делает за нас

2020-09-30 18:38 UTC, ILoyso approved these changes

2020-09-30 18:38 UTC, merged